import { readFile, writeFile, mkdir, readdir, rm } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { format, resolveConfig } from 'prettier';

const generated = '// Generated by npm run generate. Edit recipes/<name>/ instead.\n';

export function renderCode(records) {
  const files = new Map();
  const base = `${generated}export { createClient } from './client.js';\nexport type { DecisionClient, DecisionStatus, RecipeOptions, ResultMetadata } from './schema.js';\nexport { listRecipes, describeRecipe } from '../catalog/index.js';\nexport type { RecipeFilters, RecipeName, RecipeCategory, RecipeMetadata, CatalogRecipe, RecipeDescription } from '../catalog/index.js';\n`;
  files.set(
    'src/index.ts',
    base +
      records
        .map((recipe) =>
          [
            `export { ${recipe.values.join(', ')} } from '../recipes/${recipe.id}/index.js';`,
            recipe.types.length
              ? `export type { ${recipe.types.join(', ')} } from '../recipes/${recipe.id}/index.js';`
              : '',
          ]
            .filter(Boolean)
            .join('\n'),
        )
        .join('\n'),
  );
  files.set(
    'catalog/generated/names.ts',
    `${generated}export const recipeNames = ${JSON.stringify(records.map(({ id }) => id))} as const;\n`,
  );
  files.set(
    'catalog/generated/metadata.ts',
    `${generated}import type { CatalogRecipe } from '../index.js';\nexport const recipeMetadata: CatalogRecipe[] = ${JSON.stringify(records.map(({ metadata }) => metadata))};\n`,
  );
  files.set(
    'catalog/generated/loaders.ts',
    `${generated}import type { RecipeName } from '../schema.js';\nimport type { RecipeRunner } from '../runner.js';\nexport const recipeLoaders: Record<RecipeName, () => Promise<RecipeRunner>> = {\n${records.map((recipe) => `${JSON.stringify(recipe.id)}: () => import('../../recipes/${recipe.id}/index.js').then((recipe) => (input, options) => recipe.${recipe.functionName}(recipe.${recipe.inputName}.parse(input), options)),`).join('\n')}\n};\n`,
  );
  for (const recipe of records) {
    files.set(
      `catalog/generated/details/${recipe.id}.json`,
      JSON.stringify({ inputSchema: recipe.inputSchema, resultSchema: recipe.resultSchema }),
    );
  }
  return files;
}

export function renderExports(records) {
  const entry = (path) => ({ types: `./dist/${path}.d.ts`, import: `./dist/${path}.js` });
  return {
    '.': entry('src/index'),
    './catalog': entry('catalog/index'),
    './package.json': './package.json',
    ...Object.fromEntries(records.map(({ id }) => [`./${id}`, entry(`recipes/${id}/index`)])),
  };
}

export function replaceSection(text, name, content) {
  const start = `<!-- BEGIN GENERATED: ${name} -->`;
  const end = `<!-- END GENERATED: ${name} -->`;
  const first = text.indexOf(start);
  const last = text.indexOf(end);
  if (
    first < 0 ||
    last < first ||
    text.indexOf(start, first + start.length) !== -1 ||
    text.indexOf(end, last + end.length) !== -1
  ) {
    throw new Error(`Expected one pair of generated ${name} markers.`);
  }
  return (
    text.slice(0, first) + `${start}\n\n${content.trim()}\n\n${end}` + text.slice(last + end.length)
  );
}

export async function writeOutputs(root, files, check = false) {
  const config = await resolveConfig(join(root, 'package.json'));
  const stale = [];
  for (const [path, content] of files) {
    const formatted = await format(content, { ...config, filepath: path });
    const target = join(root, path);
    const previous = await readFile(target, 'utf8').catch((error) => {
      if (error.code === 'ENOENT') return '';
      throw error;
    });
    if (previous === formatted) continue;
    stale.push(path);
    if (!check) {
      await mkdir(dirname(target), { recursive: true });
      await writeFile(target, formatted);
    }
  }
  const expectedDetails = new Set(
    [...files.keys()]
      .filter((path) => path.startsWith('catalog/generated/details/'))
      .map((path) => path.split('/').at(-1)),
  );
  const directory = join(root, 'catalog/generated/details');
  for (const name of await readdir(directory).catch((error) => {
    if (error.code === 'ENOENT') return [];
    throw error;
  })) {
    if (expectedDetails.has(name)) continue;
    stale.push(`catalog/generated/details/${name}`);
    if (!check) await rm(join(directory, name));
  }
  if (check && stale.length)
    throw new Error(
      `Generated files are stale:\n${stale.map((path) => `  ${path}`).join('\n')}\nRun make docs, then commit the generated changes.`,
    );
  return stale;
}
